[pytest]
filterwarnings =
    ignore:`torch_geometric\.distributed` has been deprecated.*:DeprecationWarning:torch_geometric\.llm\.utils\.backend_utils
    ignore:`torch\.jit\.script` is not supported in Python 3\.14\+.*:DeprecationWarning:torch\.jit\._script
    ignore:Failing to pass a value to the 'type_params' parameter of 'typing\._eval_type'.*:DeprecationWarning:torch_geometric\.inspector
